# ENTREGA 1 — Dois segmentos e um serviço

name: e1

x-host: &host
  image: redes-lab-base:1
  cap_add: [NET_ADMIN]
  command: ["sh","-c","ip route del default 2>/dev/null || true; exec sleep infinity"]

services:
  host-a1:
    <<: *host
    container_name: e1-host-a1
    networks: {seg-a: {ipv4_address: 10.0.10.10}}

  host-a2:
    <<: *host
    container_name: e1-host-a2
    networks: {seg-a: {ipv4_address: 10.0.10.11}}

  srv-a:
    image: redes-lab-base:1
    container_name: e1-srv-a
    cap_add: [NET_ADMIN]
    command:
      - sh
      - -c
      - |
        ip route del default 2>/dev/null || true
        echo "servidor srv-a, segmento A, 10.0.10.20" > /srv/index.html
        exec httpd -f -p 8080 -h /srv
    networks: {seg-a: {ipv4_address: 10.0.10.20}}

  host-b1:
    <<: *host
    container_name: e1-host-b1
    networks: {seg-b: {ipv4_address: 10.0.20.10}}

  host-b2:
    <<: *host
    container_name: e1-host-b2
    networks: {seg-b: {ipv4_address: 10.0.20.11}}

networks:
  seg-a:
    driver: bridge
    ipam: {config: [{subnet: 10.0.10.0/24}]}

  seg-b:
    driver: bridge
    ipam: {config: [{subnet: 10.0.20.0/24}]}
